package compute

const (
	ELASTIC_SEARCH_STATUS_AVAILABLE   = "available"
	ELASTIC_SEARCH_STATUS_UNAVAILABLE = "unavailable"
	ELASITC_SEARCH_STATUS_CREATING    = "creating"
	ELASTIC_SEARCH_STATUS_DELETING    = "deleting"
)
