package compute

const (
	INTER_VPC_NETWORK_STATUS_AVAILABLE = "available"
	INTER_VPC_NETWORK_STATUS_CREATING  = "creating"
	INTER_VPC_NETWORK_STATUS_DELETING  = "deleting"
	INTER_VPC_NETWORK_STATUS_UNKNOWN   = "unknown"
)
