package compute

const (
	MODELARTS_POOL_SKU_AVAILABLE = "available"
	MODELARTS_POOL_SKU_SOLDOUT   = "soldout"

	MODELARTS_POOL_SKU_X86 = "x86"
	MODELARTS_POOL_SKU_ARM = "arm64"

	MODELARTS_POOL_SKU_CPU    = "CPU"
	MODELARTS_POOL_SKU_GPU    = "GPU"
	MODELARTS_POOL_SKU_ASCEND = "ASCEND"
)
