package compute

const (
	NETWORK_INTERFACE_ASSOCIATE_TYPE_SERVER       = "server"
	NETWORK_INTERFACE_ASSOCIATE_TYPE_RESERVED     = "reserved"
	NETWORK_INTERFACE_ASSOCIATE_TYPE_LOADBALANCER = "loadbalancer"
	NETWORK_INTERFACE_ASSOCIATE_TYPE_VIP          = "vip"
	NETWORK_INTERFACE_ASSOCIATE_TYPE_DHCP         = "dhcp"

	NETWORK_INTERFACE_STATUS_CREATING  = "creating"
	NETWORK_INTERFACE_STATUS_AVAILABLE = "available"
	NETWORK_INTERFACE_STATUS_DISABLED  = "disabled"
	NETWORK_INTERFACE_STATUS_ATTACHING = "attaching"
	NETWORK_INTERFACE_STATUS_DETACHING = "detaching"
	NETWORK_INTERFACE_STATUS_DELETING  = "deleting"
	NETWORK_INTERFACE_STATUS_UNKNOWN   = "unknown"
)
