package compute

const (
	VPC_PEERING_CONNECTION_STATUS_CREATING       = "creating"
	VPC_PEERING_CONNECTION_STATUS_PENDING_ACCEPT = "pending-acceptance"
	VPC_PEERING_CONNECTION_STATUS_ACTIVE         = "active"
	VPC_PEERING_CONNECTION_STATUS_DELETING       = "deleting"
	VPC_PEERING_CONNECTION_STATUS_UNKNOWN        = "unknown"
)
